# Generated by Django 6.0.6 on 2026-07-06 18:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tm_id", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Coach",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Confederation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_finished", models.BooleanField(default=False)),
                ("winner", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "current_turn",
                    models.CharField(
                        choices=[("X", "X"), ("O", "O")], default="X", max_length=1
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "confederation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="countries",
                        to="game.confederation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ColRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.IntegerField()),
                ("field", models.CharField(max_length=50)),
                ("value", models.CharField(max_length=100)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="col_rules",
                        to="game.game",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row", models.IntegerField()),
                ("col", models.IntegerField()),
                (
                    "player_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("symbol", models.CharField(blank=True, max_length=1, null=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cells",
                        to="game.game",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tm_id", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("name_in_home_country", models.CharField(max_length=100)),
                ("is_retired", models.BooleanField(default=False)),
                ("market_value", models.FloatField(default=0)),
                ("player_slug", models.CharField(max_length=150)),
                ("hnl_nastupi", models.IntegerField(default=0)),
                ("kup_nastupi", models.IntegerField(default=0)),
                ("superkup_nastupi", models.IntegerField(default=0)),
                ("a_repka_nastupi", models.IntegerField(default=0)),
                ("hnl_golovi", models.IntegerField(default=0)),
                ("finale_kupa_nastupi", models.IntegerField(default=0)),
                ("finale_kupa_golovi", models.IntegerField(default=0)),
                ("superkup_golovi", models.IntegerField(default=0)),
                ("najbolji_strijelac", models.IntegerField(default=0)),
                ("hnl_naslovi", models.IntegerField(default=0)),
                ("kup_naslovi", models.IntegerField(default=0)),
                ("superkup_naslovi", models.IntegerField(default=0)),
                (
                    "clubs",
                    models.ManyToManyField(related_name="players", to="game.club"),
                ),
                (
                    "countries",
                    models.ManyToManyField(related_name="players", to="game.country"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RowRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.IntegerField()),
                ("field", models.CharField(max_length=50)),
                ("value", models.CharField(max_length=100)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="row_rules",
                        to="game.game",
                    ),
                ),
            ],
        ),
    ]
