# Generated by Django 6.0.6 on 2026-07-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coach",
            name="tm_id",
            field=models.CharField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
