# Generated by Django 6.0.6 on 2026-06-27 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_game_cell"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cell",
            name="rules",
        ),
        migrations.CreateModel(
            name="ColRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.IntegerField()),
                ("field", models.CharField(max_length=50)),
                ("value", models.CharField(max_length=100)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="col_rules",
                        to="game.game",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RowRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.IntegerField()),
                ("field", models.CharField(max_length=50)),
                ("value", models.CharField(max_length=100)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="row_rules",
                        to="game.game",
                    ),
                ),
            ],
        ),
    ]
