# Generated by Django 6.0.7 on 2026-07-17 10:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_player_search_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('best_of', models.IntegerField(default=3)),
                ('categories', models.JSONField(default=list)),
                ('x_wins', models.IntegerField(default=0)),
                ('o_wins', models.IntegerField(default=0)),
                ('is_finished', models.BooleanField(default=False)),
                ('winner', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='game_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='game',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='game.match'),
        ),
    ]