# Generated by Django 6.0.6 on 2026-06-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_remove_cell_rules_colrule_rowrule"),
    ]

    operations = [
        migrations.AddField(
            model_name="cell",
            name="symbol",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="current_turn",
            field=models.CharField(
                choices=[("X", "X"), ("O", "O")], default="X", max_length=1
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="is_finished",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="game",
            name="winner",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
